# Generated by Django 4.2.6 on 2023-11-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role_alter_user_name_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
