# Generated by Django 4.2.6 on 2023-11-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Chief', 'Chief')], max_length=40),
        ),
    ]
