# Generated by Django 4.2.6 on 2023-11-05 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenOrphanage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('values', models.TextField()),
                ('needs', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='orphanage_imgs/')),
                ('visit', models.PositiveIntegerField(blank=True, default=0)),
                ('needs_clothes', models.IntegerField(blank=True, default=0)),
                ('needs_hygiene_supplies', models.IntegerField(blank=True, default=0)),
                ('needs_food', models.IntegerField(blank=True, default=0)),
                ('needs_money', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('children_orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_visits', to='user.childrenorphanage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField()),
                ('date_reviewed', models.DateTimeField(auto_now_add=True)),
                ('children_orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.childrenorphanage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('donated_item', models.CharField(blank=True, choices=[('clothes', 'Clothes'), ('hygiene', 'Hygiene Supplies'), ('food', 'Food'), ('money', 'Money')], max_length=20)),
                ('children_orphanage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.childrenorphanage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
